### ISSUE TITLE
Feedback

### ISSUE THREAD

**Issue by yedhukrishnan** [nitinstp23/movie_aggregator#1]
When I was going through the code, I found the following. Please try to answer/take care of the these along with your new changes:
- I see the user has to create two files (like `lib/aggregator/formats/pdf.rb` and `lib/aggregator/formats/pdf/source_file.rb`) to add a new extension. I believe this can be simplified. Can you modify it in such a way that user has to add _only a single file_, instead of two?
- I see a lot of duplication in `pdf.rb` and `text.rb`.
- In this code, every file is either an inner class or module of class `Aggregator` which is extended from `Thor`. In `lib/aggregator/formats/pdf.rb`, `Thor` class is inherited to `Aggregator` as well as `Pdf`! Can you tell me why these are necessary?

You can reply me via email when you are ready with your modified version.

**Comment by nitinstp23** [comment]
Hey @yedhukrishnan,
Answering the above questions/concerns you have raised one by one -
1. Yes. We can simplify the code to add a new extension (`text`/`pdf`) to just one file.
2. Yes there is duplication in `pdf.rb` & `text.rb` and can be reduced by adding a `BaseClass` from which every extension should inherit.
3. The reason why the `Aggregator` class extends from `Thor` is because inside this class we dynamically load and add other extensions as `subcommand`, and `Thor` automatically handles passing command line args to the subclasses defined inside it.

I'm working on the above fixes and will update you once done. :+1:
